language: python
fast_finish: true

python:
  - 3.6
  - 3.5

os:
  - linux
  
group: travis_latest

env: FC=gfortran


git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

install: python -m pip install -e .[tests]

script: coverage run tests/test_all.py -v

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then coveralls; fi
