name: ci

on:
  push:
    paths-ignore:
    - "**/*.md"
  pull_request:
    paths-ignore:
    - "**/*.md"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: sudo apt install -yq --no-install-recommends gfortran ninja-build
    - run: pip install -e .[tests,lint]
    - run: flake8
    - run: mypy .
    - run: pytest -r a -v

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install gcc ninja
    - run: pip install -e .[tests]
    - run: pytest -r a -v

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: cinst -y ninja
    - run: echo "[build]`ncompiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg
      shell: powershell
    - run: pip install -e .[tests]
    - run: pytest -r a -v